name: Android CI - Master

on:
  push:
    branches: [ master ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
        
  sign_and_release:
    name: Sign and release
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate Release AAB
      run: ./gradlew bundleRelease
    - name: Sign Bundle
      uses: r0adkll/sign-android-release@v1
      id: sign_bundle
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    - name: Deploy Bundle to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.cwlarson.deviceid
        track: production
        releaseFiles: ${{steps.sign_bundle.outputs.signedReleaseFile}}
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        whatsNewDirectory: .github/whatsnew