name: Android CI - Master

on:
  push:
    branches: [ master ]

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Unit tests
      run: ./gradlew testDebugUnitTest --stacktrace
      
  android_tests:
    name: Run instrumented tests
    runs-on: [ macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: playstore
        emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
        script: ./gradlew connectedCheck --stacktrace
        
  sign_and_release:
    name: Sign and release
    needs: [ unit_tests, android_tests ]
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate Release ABB
      run: ./gradlew bundleRelease
    - name: Sign Bundle
      uses: r0adkll/sign-android-release@v1
      id: sign_bundle
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "31.0.0"
    - name: Deploy Bundle to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.cwlarson.deviceid
        track: production
        releaseFiles: ${{steps.sign_bundle.outputs.signedReleaseFile}}
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        whatsNewDirectory: .github/whatsnew