name: GitHub Releases

on:
  push:
    tags: ['*']
    
jobs:
  github_release:
    name: Create Github Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        makeLatest: true
        name: v${{ github.ref_name }}
        bodyFile: .github/whatsnew/whatsnew-en-US